.ifndef _BACKGROUNDDATA_INC

_BACKGROUNDSDATA_INC  =1





EndScreen_at:
	.incbin "../graphics/Backgrounds/EndScreen_at.rle"

EndScreen_bg:
	.incbin "../graphics/Backgrounds/EndScreen_bg.rle"

GameOver_at:
	.incbin "../graphics/Backgrounds/GameOver_at.rle"

GameOver_bg:
	.incbin "../graphics/Backgrounds/GameOver_bg.rle"

House_at:
	.incbin "../graphics/Backgrounds/House_at.rle"

House_bg:
	.incbin "../graphics/Backgrounds/House_bg.rle"

Instructions_at:
	.incbin "../graphics/Backgrounds/Instructions_at.rle"

Instructions_bg:
	.incbin "../graphics/Backgrounds/Instructions_bg.rle"

Intro_1_at:
	.incbin "../graphics/Backgrounds/Intro_1_at.rle"

Intro_1_bg:
	.incbin "../graphics/Backgrounds/Intro_1_bg.rle"

Intro_2_at:
	.incbin "../graphics/Backgrounds/Intro_2_at.rle"

Intro_2_bg:
	.incbin "../graphics/Backgrounds/Intro_2_bg.rle"

Intro_3_at:
	.incbin "../graphics/Backgrounds/Intro_3_at.rle"

Intro_3_bg:
	.incbin "../graphics/Backgrounds/Intro_3_bg.rle"

Intro_4_at:
	.incbin "../graphics/Backgrounds/Intro_4_at.rle"

Intro_4_bg:
	.incbin "../graphics/Backgrounds/Intro_4_bg.rle"

Lake_sign_at:
	.incbin "../graphics/Backgrounds/Lake_sign_at.rle"

Lake_sign_bg:
	.incbin "../graphics/Backgrounds/Lake_sign_bg.rle"

Level_1_1_at:
	.incbin "../graphics/Backgrounds/Level_1_1_at.rle"

Level_1_1_bg:
	.incbin "../graphics/Backgrounds/Level_1_1_bg.rle"

Level_1_2_at:
	.incbin "../graphics/Backgrounds/Level_1_2_at.rle"

Level_1_2_bg:
	.incbin "../graphics/Backgrounds/Level_1_2_bg.rle"

Level_1_3_at:
	.incbin "../graphics/Backgrounds/Level_1_3_at.rle"

Level_1_3_bg:
	.incbin "../graphics/Backgrounds/Level_1_3_bg.rle"

Level_1_4_at:
	.incbin "../graphics/Backgrounds/Level_1_4_at.rle"

Level_1_4_bg:
	.incbin "../graphics/Backgrounds/Level_1_4_bg.rle"

Level_2_1_at:
	.incbin "../graphics/Backgrounds/Level_2_1_at.rle"

Level_2_1_bg:
	.incbin "../graphics/Backgrounds/Level_2_1_bg.rle"

Level_2_2_at:
	.incbin "../graphics/Backgrounds/Level_2_2_at.rle"

Level_2_2_bg:
	.incbin "../graphics/Backgrounds/Level_2_2_bg.rle"

Level_2_3_at:
	.incbin "../graphics/Backgrounds/Level_2_3_at.rle"

Level_2_3_bg:
	.incbin "../graphics/Backgrounds/Level_2_3_bg.rle"

Level_3_1_at:
	.incbin "../graphics/Backgrounds/Level_3_1_at.rle"

Level_3_1_bg:
	.incbin "../graphics/Backgrounds/Level_3_1_bg.rle"

Level_3_2_at:
	.incbin "../graphics/Backgrounds/Level_3_2_at.rle"

Level_3_2_bg:
	.incbin "../graphics/Backgrounds/Level_3_2_bg.rle"

Level_3_3_at:
	.incbin "../graphics/Backgrounds/Level_3_3_at.rle"

Level_3_3_bg:
	.incbin "../graphics/Backgrounds/Level_3_3_bg.rle"

Level_3_4_at:
	.incbin "../graphics/Backgrounds/Level_3_4_at.rle"

Level_3_4_bg:
	.incbin "../graphics/Backgrounds/Level_3_4_bg.rle"

Level_3_5_at:
	.incbin "../graphics/Backgrounds/Level_3_5_at.rle"

Level_3_5_bg:
	.incbin "../graphics/Backgrounds/Level_3_5_bg.rle"

Market_Sign_at:
	.incbin "../graphics/Backgrounds/Market_Sign_at.rle"

Market_Sign_bg:
	.incbin "../graphics/Backgrounds/Market_Sign_bg.rle"

SkatePark_sign_at:
	.incbin "../graphics/Backgrounds/SkatePark_sign_at.rle"

SkatePark_sign_bg:
	.incbin "../graphics/Backgrounds/SkatePark_sign_bg.rle"

TitleScreen_at:
	.incbin "../graphics/Backgrounds/TitleScreen_at.rle"

TitleScreen_bg:
	.incbin "../graphics/Backgrounds/TitleScreen_bg.rle"

WinScreen_at:
	.incbin "../graphics/Backgrounds/WinScreen_at.rle"

WinScreen_bg:
	.incbin "../graphics/Backgrounds/WinScreen_bg.rle"

.endif