; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Drummier Drums:

.export _music_data_drummier_drums:=music_data_drummier_drums

music_data_drummier_drums:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Did You Say More Drums?
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_drummier_drums
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env8,@env11,@env13,@env0 ; 00 : Noise: High Hat 1
	.word @env3,@env11,@env13,@env0 ; 01 : Noise: High Hat DCPM backing
	.word @env7,@env11,@env13,@env0 ; 02 : Triangle: Bass 1
	.word @env7,@env4,@env13,@env0 ; 03 : Triangle: Bass 2
	.word @env2,@env11,@env14,@env0 ; 04 : Square: Lead long rise
	.word @env16,@env11,@env14,@env0 ; 05 : Square: Lead 4 rise
	.word @env6,@env11,@env14,@env0 ; 06 : Square: Fall
	.word @env18,@env11,@env14,@env0 ; 07 : Square: Lead long rise Loud
	.word @env1,@env11,@env14,@env0 ; 08 : Square: Fall Loud
	.word @env15,@env9,@env13,@env0 ; 09 : Triangle: Ramp Up
	.word @env5,@env11,@env14,@env0 ; 0a : Square: Lead long rise to fade
	.word @env12,@env11,@env14,@env10 ; 0b : Square: Lead long rise Loud vibration
	.word @env15,@env11,@env13,@env0 ; 0c : Triangle: 1st off
	.word @env19,@env11,@env14,@env10 ; 0d : Square: Lead long rise Loud vibration to fade
	.word @env17,@env11,@env14,@env0 ; 0e : Square: Lead long rise fade 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c7,$c5,$c3,$c3,$c2,$00,$05
@env2:
	.byte $00,$c3,$03,$c4,$02,$c5,$07,$c6,$00,$07
@env3:
	.byte $00,$c7,$c7,$c5,$03,$c4,$06,$c3,$0d,$c2,$0a,$c1,$00,$0b
@env4:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$c0,$00,$08
@env5:
	.byte $00,$c3,$03,$c4,$02,$c5,$05,$c6,$3a,$c5,$10,$c4,$0d,$c3,$0d,$c2,$0f,$c1,$0e,$c0,$00,$13
@env6:
	.byte $00,$c5,$c4,$c3,$c3,$c2,$00,$05
@env7:
	.byte $00,$cf,$7f,$00,$02
@env8:
	.byte $00,$ca,$c7,$c5,$c3,$c1,$c0,$00,$06
@env9:
	.byte $c0,$bf,$be,$bd,$c0,$00,$04
@env10:
	.byte $00,$c0,$13,$c0,$c3,$c6,$c3,$c0,$bd,$ba,$bd,$c0,$00,$03
@env11:
	.byte $c0,$7f,$00,$01
@env12:
	.byte $00,$c2,$c4,$c5,$c5,$c6,$02,$c7,$07,$c8,$09,$c9,$00,$0b
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $c2,$7f,$00,$00
@env15:
	.byte $00,$c0,$cf,$00,$02
@env16:
	.byte $00,$c0,$c1,$c2,$c2,$c3,$c4,$c5,$c6,$02,$c7,$00,$0a
@env17:
	.byte $00,$c6,$0e,$c5,$0a,$c4,$05,$c3,$0c,$c2,$0e,$c1,$12,$c0,$00,$0d
@env18:
	.byte $00,$c2,$c4,$c5,$c5,$c6,$02,$c7,$07,$c8,$00,$09
@env19:
	.byte $00,$c2,$c4,$c5,$c5,$c6,$02,$c7,$07,$c8,$09,$c9,$3c,$c8,$09,$c7,$08,$c6,$07,$c5,$09,$c4,$0a,$c3,$0c,$c2,$0b,$c1,$00,$1b

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 00 CRASH 1 (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$66,$0f,$40 ; 01 KICK 2 (Pitch:15)
	.byte $5a+.lobyte(FAMISTUDIO_DPCM_PTR),$4c,$0f,$40 ; 02 KICK 4 (Pitch:15)
	.byte $6e+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 03 KICK 5 (Pitch:15)
	.byte $7d+.lobyte(FAMISTUDIO_DPCM_PTR),$43,$0f,$40 ; 04 KICK 7 (Pitch:15)
	.byte $8e+.lobyte(FAMISTUDIO_DPCM_PTR),$7e,$0f,$40 ; 05 SNARE 1 (Pitch:15)
	.byte $11+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 06 SNARE 2 (Pitch:15)
	.byte $fe+.lobyte(FAMISTUDIO_DPCM_PTR),$4b,$0f,$40 ; 07 SNARE 3 (Pitch:15)
	.byte $e9+.lobyte(FAMISTUDIO_DPCM_PTR),$50,$0f,$40 ; 08 SNARE 4 (Pitch:15)
	.byte $d2+.lobyte(FAMISTUDIO_DPCM_PTR),$5b,$0f,$40 ; 09 SNARE 6 (Pitch:15)
	.byte $ae+.lobyte(FAMISTUDIO_DPCM_PTR),$8f,$0f,$40 ; 0a SNARE 7 (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $ff, $bf
@song0ref4:
	.byte $48, $ff, $ff, $bf
@song0ref8:
	.byte $48, $ff, $ff, $bf, $48, $ff, $ff, $bf
@song0ref16:
	.byte $48, $88
@song0ref18:
	.byte $14, $a5, $11, $a5, $14, $a5, $11, $a5, $16, $cd, $18, $a5, $1b, $91, $1f, $91, $48, $94, $1b, $ff, $ed, $00, $cd
	.byte $41, $19
	.word @song0ref4
@song0ref44:
	.byte $48, $1b, $ff, $9d, $13, $cd, $18, $cd
@song0ref52:
	.byte $48, $11, $91, $8a
@song0ref56:
	.byte $11, $87, $11, $91, $11, $91, $11, $87, $11, $91, $11, $87, $11, $91, $11, $91, $14, $87, $88, $13, $91, $8a, $13, $87
	.byte $13, $91, $13, $91, $16, $87, $88, $18, $91, $8a, $18, $87, $18, $91, $18, $91, $1b, $87, $48, $88, $1b, $ff, $9d, $13
	.byte $cd, $18, $a5, $0f, $a5, $48
	.byte $41, $10
	.word @song0ref18
	.byte $48, $1b, $ff, $9d, $13, $cd, $18, $a5, $0f, $a5
	.byte $41, $28
	.word @song0ref52
	.byte $48, $94, $1b, $ff, $ed, $00, $cd, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $8e, $11, $91
	.byte $41, $12
	.word @song0ref56
@song0ref148:
	.byte $13, $91, $13, $87, $13, $91, $13, $91, $16, $87, $18, $91, $18, $87, $18, $91, $18, $91, $1b, $87, $48, $1b, $ff, $9d
	.byte $13, $cd, $18, $a5, $0f, $a5, $48
	.byte $41, $10
	.word @song0ref18
	.byte $48, $96, $1b, $ff, $9d, $8e, $13, $cd, $18, $cd, $48, $11, $91
	.byte $41, $12
	.word @song0ref56
	.byte $41, $14
	.word @song0ref148
	.byte $48, $96, $1b, $ff, $9d, $8e, $13, $cd, $0f, $cd, $48, $11, $91
	.byte $41, $12
	.word @song0ref56
	.byte $41, $1d
	.word @song0ref148
	.byte $48
	.byte $41, $10
	.word @song0ref18
	.byte $48, $96, $1b, $ff, $9d, $8e, $1f, $cd, $9a, $24, $cd, $48, $ff, $ff, $bf, $48, $00, $ff, $ff, $bd, $48, $8e
	.byte $41, $10
	.word @song0ref18
	.byte $48, $96, $1b, $ff, $9d, $88, $1f, $cd, $24, $cd, $48, $11, $ff, $9d, $16, $cd, $1b, $cd, $48, $1f, $ff, $9d, $16, $cd
	.byte $1b, $cd, $48, $00, $ff, $ff, $bd, $48, $14, $a5, $11, $a5, $14, $a5, $11, $a5, $16, $cd, $18, $cd, $48, $11, $ff, $9d
	.byte $0f, $cd, $0d, $cd, $48, $00, $ff, $ff, $bd, $48, $ff, $ff, $bf, $48
	.byte $41, $10
	.word @song0ref18
	.byte $48, $24, $ff, $9d, $94, $25, $ff, $9d, $48, $9c, $25, $ff, $9d, $00, $ff, $9d
	.byte $41, $10
	.word @song0ref16
	.byte $41, $38
	.word @song0ref44
	.byte $48
	.byte $41, $10
	.word @song0ref18
	.byte $41, $38
	.word @song0ref44
	.byte $48, $1b, $a5, $18, $a5, $14, $cd, $19, $cd, $1b, $cd, $48, $94, $14, $ff, $ed, $00, $cd
	.byte $41, $16
	.word @song0ref8
	.byte $41, $38
	.word @song0ref44
	.byte $48
	.byte $41, $10
	.word @song0ref18
	.byte $41, $38
	.word @song0ref44
	.byte $48, $00, $ff, $ff, $bd, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff
	.byte $bf, $44, $00
@song0ch1:
@song0ref402:
	.byte $8c
@song0ref403:
	.byte $1d, $91, $20, $91, $1d, $91, $20, $91, $1d, $91, $24, $91, $1d, $91, $20, $91, $1d, $91, $20, $91, $1d, $91, $24, $91
	.byte $1d, $91, $20, $91, $1d, $91, $20, $91, $1f, $91, $22, $91, $1f, $91, $22, $91, $1f, $91, $25, $91, $1f, $91, $22, $91
	.byte $1f, $91, $22, $91, $1f, $91, $25, $91, $1f, $91, $22, $91, $1f, $91, $22, $91, $1b, $91, $1f, $91, $1b, $91, $1f, $91
	.byte $1b, $91, $22, $91, $1b, $91, $1f, $91, $1b, $91, $1f, $91, $1b, $91, $22, $91, $1b, $91, $1f, $91, $1b, $91, $1f, $91
@song0ref499:
	.byte $20, $91, $24, $91, $20, $91, $24, $91, $20, $91, $27, $91, $20, $91, $24, $91, $19, $91, $1d, $91, $19, $91, $20, $91
	.byte $1b, $91, $1f, $91, $1b, $91, $1f, $91
@song0ref531:
	.byte $20, $91, $20, $91, $1d, $91, $1d, $91, $20, $91, $20, $91, $1d, $91, $1d, $91, $22, $91, $22, $91, $22, $91, $22, $91
	.byte $24, $91, $24, $91, $29, $91, $2c, $91
@song0ref563:
	.byte $30, $91, $30, $91, $30, $91, $30, $91, $30, $91, $30, $91, $30, $91, $30
@song0ref578:
	.byte $91, $27, $91, $27, $91, $27, $91, $27, $91, $2c, $91, $2c, $91, $2c, $91, $2c, $91, $25, $91, $25, $91, $25, $91, $25
	.byte $91, $25, $91, $25, $91, $25, $91, $25
	.byte $41, $11
	.word @song0ref578
	.byte $41, $40
	.word @song0ref403
	.byte $41, $4f
	.word @song0ref531
	.byte $41, $11
	.word @song0ref578
	.byte $41, $20
	.word @song0ref563
	.byte $41, $4f
	.word @song0ref531
	.byte $41, $11
	.word @song0ref578
	.byte $41, $20
	.word @song0ref563
	.byte $41, $40
	.word @song0ref403
	.byte $90, $25, $91, $29, $91, $2c, $91, $31, $91, $25, $91, $29, $91, $2c, $91, $31
@song0ref653:
	.byte $91, $27, $91, $2b, $91, $2e, $91, $33, $91, $2c, $91, $30, $91, $33, $91, $38
@song0ref669:
	.byte $91, $30, $91, $33, $91, $37, $91, $3c, $91, $30, $91, $33, $91, $37, $91, $3c
	.byte $41, $11
	.word @song0ref653
@song0ref688:
	.byte $2c, $91, $2c, $91, $29, $91, $29, $91, $2c, $91, $2c, $91, $29, $91, $29, $91, $2e, $91, $2e, $91, $2e, $91, $2e, $91
	.byte $29, $91, $29, $91, $2e, $91, $31
	.byte $41, $10
	.word @song0ref669
	.byte $41, $11
	.word @song0ref653
@song0ref725:
	.byte $25, $91, $29, $91, $2c, $91, $31, $91, $2c, $91, $29, $91, $25, $91, $29, $91, $2b
@song0ref742:
	.byte $91, $2e, $91, $2b, $91, $27, $91, $24, $91, $27, $91, $2c, $91, $30, $91
@song0ref757:
	.byte $33, $91, $37, $91, $33, $91, $30, $91, $2b, $91, $27, $91, $2b, $91, $30, $91, $33
	.byte $41, $0f
	.word @song0ref742
	.byte $41, $31
	.word @song0ref725
	.byte $41, $0f
	.word @song0ref742
	.byte $2c, $91, $29, $91, $2c, $91, $30, $91, $2c, $91, $29, $91, $24, $91, $20, $91, $22, $91, $25, $91, $29, $91, $2e, $91
	.byte $30, $91, $35, $91, $38, $91, $3c, $91
@song0ref815:
	.byte $3f, $91, $37, $91, $33, $91, $30, $91, $33, $91, $37, $91, $3c, $91, $3f, $91, $40, $4f, $91, $40, $52, $91, $40, $4f
	.byte $91, $3f, $91, $3c, $91, $3f, $91, $40, $50, $91, $40, $54, $91
	.byte $41, $40
	.word @song0ref402
	.byte $41, $18
	.word @song0ref531
	.byte $1d, $91, $1d, $91, $22, $91, $25, $91, $90
	.byte $41, $11
	.word @song0ref757
	.byte $41, $0f
	.word @song0ref742
	.byte $8c
@song0ref874:
	.byte $19, $91, $19, $91, $19, $91, $19, $91, $19, $91, $19, $91, $19, $91, $19
@song0ref889:
	.byte $91, $1b, $91, $1b, $91, $1b, $91, $1b, $91, $20, $91, $20, $91, $20, $91, $20
@song0ref905:
	.byte $91, $24, $91, $24, $91, $24, $91, $24, $91, $24, $91, $24, $91, $24, $91, $24
	.byte $41, $11
	.word @song0ref889
	.byte $90
	.byte $41, $20
	.word @song0ref499
	.byte $8c
	.byte $41, $18
	.word @song0ref531
	.byte $1d, $91, $1d, $91, $22, $91, $25
	.byte $41, $10
	.word @song0ref905
	.byte $41, $11
	.word @song0ref889
	.byte $41, $40
	.word @song0ref403
	.byte $90
	.byte $41, $1f
	.word @song0ref688
	.byte $91, $29, $91, $29, $91, $2c, $91, $2c, $91, $29, $91, $29, $91, $2c, $91, $2c, $91, $2b, $91, $2b, $91, $2e, $91, $2e
	.byte $91, $2b, $91, $2b, $91, $2e, $91, $2e, $91, $00, $ff, $ff, $bd, $40, $50, $87, $40, $4d, $87, $3c, $87, $38, $87, $35
	.byte $87, $38, $87, $3c, $87, $40, $4d, $87, $3c, $87, $38, $87, $35, $87, $30, $87, $35, $87, $38, $87, $3c, $87, $40, $4d
	.byte $87, $3a, $87, $35, $87, $31, $87, $2e, $87, $35, $87, $31, $87, $2e, $87, $29
@song0ref1040:
	.byte $87, $30, $87, $2b, $87, $27, $87, $24, $87, $30, $87, $2b, $87, $27, $87, $24
@song0ref1056:
	.byte $87
@song0ref1057:
	.byte $30, $87, $33, $87, $37, $87, $3c, $87, $30, $87, $33, $87, $37, $87, $3c
	.byte $41, $10
	.word @song0ref1056
@song0ref1075:
	.byte $87, $27, $87, $2b, $87, $2e, $87, $33, $87, $27, $87, $2b, $87, $2e, $87, $33, $87, $2c, $87, $30, $87, $33, $87, $38
	.byte $87, $2c, $87, $30, $87, $33, $87, $38
@song0ref1107:
	.byte $87, $25, $87, $29, $87, $2c, $87, $31, $87, $25, $87, $29, $87, $2c, $87, $31
	.byte $41, $10
	.word @song0ref1107
	.byte $41, $21
	.word @song0ref1075
@song0ref1129:
	.byte $3c, $87, $37, $87, $33, $87, $30, $87, $3c, $87, $37, $87, $33, $87, $30
	.byte $41, $11
	.word @song0ref1040
@song0ref1147:
	.byte $27, $87, $24, $87, $1f, $87, $1b, $87, $27, $87, $24, $87, $1f, $87, $1b, $87, $20, $87, $1b, $87, $18, $87, $14, $87
	.byte $20, $87, $1b, $87, $18, $87, $14, $87
	.byte $41, $1f
	.word @song0ref688
	.byte $91
	.byte $41, $0f
	.word @song0ref1057
	.byte $41, $10
	.word @song0ref1056
	.byte $41, $30
	.word @song0ref1075
	.byte $41, $10
	.word @song0ref1107
	.byte $41, $21
	.word @song0ref1075
	.byte $41, $0f
	.word @song0ref1129
	.byte $41, $11
	.word @song0ref1040
	.byte $41, $20
	.word @song0ref1147
	.byte $18, $87, $1b, $87, $20, $87, $1b, $87, $14, $87, $18, $87, $1b, $91, $20, $91, $1b, $91, $18, $91, $14, $91, $19, $91
	.byte $1d, $91, $20, $91, $25, $91, $1b, $91, $1f, $91, $22, $91, $27, $91, $8c
	.byte $41, $2f
	.word @song0ref563
	.byte $41, $11
	.word @song0ref578
	.byte $00, $ff, $ff, $bd
	.byte $41, $20
	.word @song0ref499
	.byte $00, $ff, $ff, $bd, $ff, $ff, $bf, $90
	.byte $41, $0f
	.word @song0ref1129
	.byte $41, $11
	.word @song0ref1040
	.byte $41, $20
	.word @song0ref1147
	.byte $00, $ff, $ff, $bd
	.byte $41, $20
	.word @song0ref815
	.byte $00, $ff, $ff, $bd
	.byte $41, $11
	.word @song0ref757
	.byte $41, $0f
	.word @song0ref742
	.byte $41, $60
	.word @song0ref402
	.byte $41, $20
	.word @song0ref874
	.byte $00, $ff, $ff, $bd, $ff, $ff, $bf, $44, $00
@song0ch2:
@song0ref1309:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
@song0ref1324:
	.byte $92
@song0ref1325:
	.byte $1d, $a5, $1d, $f5, $22, $a5, $22, $f5, $19, $a5, $19, $f5, $1f, $a5, $1f, $f5
	.byte $41, $10
	.word @song0ref1325
	.byte $41, $10
	.word @song0ref1325
	.byte $41, $10
	.word @song0ref1325
	.byte $41, $10
	.word @song0ref1325
@song0ref1353:
	.byte $86, $0d, $a5, $84, $14, $91, $19, $91, $86, $0d, $a5, $84, $14, $91, $19, $91, $86, $0f, $a5, $84, $16, $91, $1b, $91
	.byte $86, $14, $a5, $84, $1b, $91, $20
@song0ref1384:
	.byte $91
@song0ref1385:
	.byte $86, $18, $a5, $84, $1f, $91, $24, $91, $86, $18, $a5, $84, $1f, $91, $24, $91, $86, $0f, $a5, $84, $16, $91, $1b, $91
	.byte $86, $14, $a5, $84, $1b, $91, $20, $91, $00, $ff, $ff, $bd, $ff, $ff, $bf
	.byte $41, $30
	.word @song0ref1353
	.byte $92, $19, $a5, $19, $f5, $1f, $a5, $1f, $f5
	.byte $41, $18
	.word @song0ref1385
	.byte $41, $30
	.word @song0ref1353
	.byte $41, $30
	.word @song0ref1353
	.byte $92, $19, $a5, $19, $f5, $1f, $a5, $1f, $f5
	.byte $41, $1f
	.word @song0ref1385
@song0ref1457:
	.byte $98
@song0ref1458:
	.byte $24, $a5, $1d, $91, $1d, $91, $24, $a5, $1d, $91, $1d, $91, $25, $a5, $25, $a5, $22, $a5, $25, $91, $29
	.byte $41, $19
	.word @song0ref1384
	.byte $0d, $a5, $14, $91, $19, $91, $0d, $a5, $14, $91, $19, $91, $0f, $a5, $16, $91, $1b, $91, $14, $a5, $1b, $91, $20, $91
@song0ref1506:
	.byte $18, $a5, $1f, $91, $24, $91, $18, $a5, $1f, $91, $24, $91, $0f, $a5, $16, $91, $1b, $91, $14, $a5, $1b, $91, $20, $91
	.byte $41, $15
	.word @song0ref1457
	.byte $91, $92, $19, $a5, $19, $f5, $1f, $a5, $1f, $f5, $84
	.byte $41, $18
	.word @song0ref1506
	.byte $98
@song0ref1548:
	.byte $1d, $cd, $20, $cd, $24, $cd, $29, $cd, $22, $cd, $25, $cd, $29, $cd, $2c, $cd
	.byte $41, $15
	.word @song0ref1458
	.byte $91, $20, $cd, $24, $cd, $22, $cd, $25, $cd, $00, $ff, $ff, $bd
@song0ref1580:
	.byte $1d, $cd, $20, $cd, $22, $cd, $27, $cd
@song0ref1588:
	.byte $24, $cd, $27, $cd, $2b, $cd, $30, $cd, $20, $cd, $25, $cd, $27, $cd, $2b, $cd, $24, $cd, $27, $cd, $2b, $cd, $30, $cd
	.byte $41, $15
	.word @song0ref1458
	.byte $91
	.byte $41, $10
	.word @song0ref1588
	.byte $2b, $ff, $9d, $24, $ff, $9d, $1b, $a5, $1b, $a5, $1b, $cd, $20, $cd, $22, $cd
	.byte $41, $10
	.word @song0ref1324
	.byte $41, $10
	.word @song0ref1325
	.byte $98
	.byte $41, $10
	.word @song0ref1588
	.byte $2b, $ff, $9d, $24, $ff, $9d
	.byte $41, $18
	.word @song0ref1580
	.byte $2b, $ff, $9d, $24, $ff, $9d
	.byte $41, $10
	.word @song0ref1548
	.byte $2b, $ff, $9d, $27, $ff, $9d, $27, $ff, $ff, $bd, $00, $ff, $ff, $bd, $ff, $ff, $bf, $44, $00
@song0ch3:
@song0ref1683:
	.byte $ff, $ff, $bf
@song0ref1686:
	.byte $ff, $ff, $bf
@song0ref1689:
	.byte $80, $15, $91, $00, $91, $15, $91, $00, $91, $82, $13, $cd, $80, $15, $91, $00, $91, $15, $91, $00, $91, $82, $13, $cd
	.byte $00, $ff, $ff, $bd
	.byte $41, $1e
	.word @song0ref1683
	.byte $41, $1e
	.word @song0ref1683
	.byte $41, $1e
	.word @song0ref1683
@song0ref1726:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
@song0ref1735:
	.byte $80, $15, $91, $00, $91, $15, $91, $00, $91, $82, $21, $cd, $80, $15, $91, $00, $91, $15, $91, $00, $91, $82, $21, $cd
	.byte $41, $14
	.word @song0ref1735
	.byte $41, $14
	.word @song0ref1735
	.byte $41, $14
	.word @song0ref1735
	.byte $41, $14
	.word @song0ref1735
	.byte $41, $14
	.word @song0ref1735
	.byte $41, $14
	.word @song0ref1735
	.byte $41, $14
	.word @song0ref1735
	.byte $41, $14
	.word @song0ref1735
	.byte $41, $14
	.word @song0ref1735
	.byte $00, $ff, $ff, $bd
	.byte $41, $17
	.word @song0ref1686
	.byte $41, $14
	.word @song0ref1689
	.byte $41, $14
	.word @song0ref1689
	.byte $41, $14
	.word @song0ref1689
	.byte $41, $14
	.word @song0ref1689
	.byte $41, $18
	.word @song0ref1689
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $9f, $21, $cd, $00, $cd
@song0ref1823:
	.byte $23, $a5, $23, $a5, $21, $a5, $00, $a5, $23, $a5, $23, $a5, $21, $a5, $00, $a5, $ff, $ff, $bf
	.byte $41, $10
	.word @song0ref1823
	.byte $41, $10
	.word @song0ref1823
	.byte $41, $10
	.word @song0ref1823
@song0ref1851:
	.byte $21, $a5, $20, $a5, $21, $a5, $20, $a5, $21, $a5, $00, $a5, $20, $a5, $20, $a5, $20, $a5, $20, $a5, $21, $a5, $00, $a5
	.byte $20, $a5, $20, $a5, $21, $a5, $00, $a5
	.byte $41, $20
	.word @song0ref1851
	.byte $41, $1d
	.word @song0ref1726
	.byte $00, $ff, $ff, $bd
	.byte $41, $14
	.word @song0ref1735
	.byte $41, $14
	.word @song0ref1735
	.byte $41, $14
	.word @song0ref1735
	.byte $41, $14
	.word @song0ref1689
	.byte $41, $18
	.word @song0ref1689
	.byte $41, $0f
	.word @song0ref1309
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $44, $00
@song0ch4:
@song0ref1920:
	.byte $05, $91, $00, $91, $05, $91, $00, $91, $01, $a5, $00, $a5, $05, $91, $00, $91, $05, $91, $00, $91, $01, $a5, $00, $a5
	.byte $41, $18
	.word @song0ref1920
@song0ref1947:
	.byte $05, $91, $00, $91, $05, $91, $00, $91, $01, $a5, $00, $a5, $05, $91, $06, $91, $05, $91, $00, $91, $01, $a5, $06, $a5
	.byte $41, $18
	.word @song0ref1920
@song0ref1974:
	.byte $05, $91, $00, $91, $05, $91, $00, $91, $01, $a5, $05, $91, $07, $91, $05, $91, $00, $91, $05, $91, $03, $91, $03, $91
	.byte $03, $91, $00, $a5
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $18
	.word @song0ref1947
	.byte $41, $18
	.word @song0ref1920
@song0ref2011:
	.byte $05, $91, $07, $91, $05, $91, $07, $91, $01, $a5, $00, $91, $09, $91, $05, $91, $07, $91, $05, $91, $02, $91, $02, $91
	.byte $02, $91, $0a, $a5
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $18
	.word @song0ref1947
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $1c
	.word @song0ref1974
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $18
	.word @song0ref1947
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $1c
	.word @song0ref2011
	.byte $93, $00, $ff, $ff, $a9
@song0ref2068:
	.byte $f7, $05, $91, $00, $91, $05, $91, $00, $91, $07, $91, $07, $91, $05, $91, $07
@song0ref2084:
	.byte $91, $01, $a5, $05, $91, $07, $91, $05, $91, $00, $91, $01, $a5, $0a, $91, $00, $91, $05, $91, $07, $91, $05, $91, $00
	.byte $91, $01, $a5, $0a, $91, $00, $91, $05, $91, $07, $91, $05, $91, $00, $91, $01, $a5, $0b, $91, $0b, $91, $09, $91, $05
	.byte $91, $09, $91, $02, $91, $02, $91, $02
	.byte $41, $29
	.word @song0ref2084
@song0ref2143:
	.byte $0a, $91, $00, $91, $05, $91, $09, $91, $05, $91, $09, $91, $09, $91, $09
	.byte $41, $38
	.word @song0ref2084
	.byte $41, $29
	.word @song0ref2084
	.byte $41, $0f
	.word @song0ref2143
	.byte $41, $38
	.word @song0ref2084
	.byte $91, $01, $a5, $00, $ff, $ff, $bd, $ff, $ff, $bf
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $1c
	.word @song0ref1974
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $18
	.word @song0ref1947
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $1c
	.word @song0ref1974
	.byte $41, $18
	.word @song0ref1920
	.byte $ff, $ff, $bf
	.byte $41, $39
	.word @song0ref2068
	.byte $41, $0f
	.word @song0ref2143
	.byte $91, $01, $a5
@song0ref2213:
	.byte $05, $91, $05, $91, $05, $91, $05, $91, $05, $87, $05, $87, $05, $87, $05, $87, $05, $87, $05, $87, $05, $87, $05, $87
	.byte $09, $91, $05, $91, $09, $91, $05, $91, $0a, $91, $0a, $91, $07, $91, $0a, $91, $07
@song0ref2254:
	.byte $91, $05, $91, $07, $91, $05, $91, $07, $91, $05, $91
@song0ref2265:
	.byte $07, $91, $05, $91, $0b, $91, $05, $91, $0b, $91, $05, $91, $0a, $91, $05, $91, $0a, $91, $05, $91
@song0ref2285:
	.byte $05, $91, $05, $91, $05, $91, $05, $91, $05, $91, $05, $91, $05, $91, $05, $91, $01, $a5, $07, $91, $05, $91, $0a, $91
	.byte $05, $91, $0a
	.byte $41, $0f
	.word @song0ref2254
	.byte $41, $1c
	.word @song0ref2265
	.byte $08, $91, $08, $91, $08, $91, $08, $91, $04, $91, $04, $91, $04, $91, $04, $91, $09, $87, $09, $87, $09, $87, $09, $87
	.byte $09, $87, $09, $87, $09, $87, $09, $87, $06, $91, $08, $91, $06, $91, $08, $91, $07, $91, $08, $91, $07, $91, $08, $91
	.byte $09, $91, $08, $91, $09, $91, $08, $91, $0a, $91, $08, $91, $0a, $91, $08, $91
	.byte $41, $28
	.word @song0ref2213
	.byte $41, $1b
	.word @song0ref2285
	.byte $41, $0f
	.word @song0ref2254
	.byte $41, $16
	.word @song0ref2265
	.byte $07, $91, $05, $91, $00, $91, $01, $a5
	.byte $41, $0f
	.word @song0ref2143
	.byte $91, $01, $a5
	.byte $41, $18
	.word @song0ref1947
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $1c
	.word @song0ref1974
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $18
	.word @song0ref1947
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $1c
	.word @song0ref1974
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $18
	.word @song0ref1947
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $1c
	.word @song0ref1974
	.byte $41, $18
	.word @song0ref1920
	.byte $41, $18
	.word @song0ref1947
	.byte $41, $18
	.word @song0ref1920
	.byte $05, $91, $00, $91, $05, $91, $00, $91, $0a, $91, $09, $91, $00, $91, $09, $91, $05, $91, $07, $91, $05, $91, $07, $91
	.byte $0a, $a5, $01, $a5, $a7, $05, $91, $02, $91, $02, $91, $02, $91, $00, $ff, $c5, $ff, $ff, $bf, $44, $00
