; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_Game_over=music_data_Game_over
.endif

music_data_Game_over:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : Get_Fucked
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_Game_over
.global FAMISTUDIO_DPCM_PTR

@instruments:

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$7f,$00,$01
@env2:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref5:
	.byte $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47
	.byte $ff, $ff, $bf, $47, $ff, $ff, $bf, $47
	.byte $41, $18
	.word @song0ref5
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref44:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $18
	.word @song0ref44
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $41, $18
	.word @song0ref44
	.byte $41, $18
	.word @song0ref44
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $18
	.word @song0ref44
	.byte $41, $18
	.word @song0ref44
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $18
	.word @song0ref44
	.byte $41, $18
	.word @song0ref44
	.byte $42
	.word @song0ch4loop
