; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Drummier Drums:

.export _music_data_intro:=music_data_intro

music_data_intro:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Intro 2
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_intro
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env8,@env10,@env0 ; 00 : Square: Lead long rise
	.word @env12,@env8,@env10,@env0 ; 01 : Square: Lead 4 rise
	.word @env4,@env8,@env10,@env0 ; 02 : Square: Lead long rise to fade
	.word @env1,@env8,@env10,@env0 ; 03 : Square: Fall Loud
	.word @env5,@env8,@env10,@env0 ; 04 : Square: Fall
	.word @env11,@env8,@env9,@env0 ; 05 : Triangle: 1st off
	.word @env11,@env7,@env9,@env0 ; 06 : Triangle: Ramp Up
	.word @env3,@env8,@env9,@env0 ; 07 : Noise: High Hat DCPM backing

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c7,$c5,$c3,$c3,$c2,$00,$05
@env2:
	.byte $00,$c3,$03,$c4,$02,$c5,$07,$c6,$00,$07
@env3:
	.byte $00,$c7,$c7,$c5,$03,$c4,$06,$c3,$0d,$c2,$0a,$c1,$00,$0b
@env4:
	.byte $00,$c3,$03,$c4,$02,$c5,$05,$c6,$3a,$c5,$10,$c4,$0d,$c3,$0d,$c2,$0f,$c1,$0e,$c0,$00,$13
@env5:
	.byte $00,$c5,$c4,$c3,$c3,$c2,$00,$05
@env6:
	.byte $00,$cf,$7f,$00,$02
@env7:
	.byte $c0,$bf,$be,$bd,$c0,$00,$04
@env8:
	.byte $c0,$7f,$00,$01
@env9:
	.byte $7f,$00,$00
@env10:
	.byte $c2,$7f,$00,$00
@env11:
	.byte $00,$c0,$cf,$00,$02
@env12:
	.byte $00,$c0,$c1,$c2,$c2,$c3,$c4,$c5,$c6,$02,$c7,$00,$0a

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$83,$0f,$40 ; 00 CRASH 1 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$2a,$0f,$40 ; 01 KICK 7 (Pitch:15)
	.byte $0b+.lobyte(FAMISTUDIO_DPCM_PTR),$5b,$0f,$40 ; 02 SNARE 1 (Pitch:15)
	.byte $5e+.lobyte(FAMISTUDIO_DPCM_PTR),$60,$0f,$40 ; 03 SNARE 2 (Pitch:15)
	.byte $4c+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0f,$40 ; 04 SNARE 3 (Pitch:15)
	.byte $38+.lobyte(FAMISTUDIO_DPCM_PTR),$4c,$0f,$40 ; 05 SNARE 4 (Pitch:15)
	.byte $22+.lobyte(FAMISTUDIO_DPCM_PTR),$56,$0f,$40 ; 06 SNARE 6 (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ref1:
	.byte $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $ff, $ff, $bf, $48, $80
@song0ref14:
	.byte $11, $91, $82, $11, $87, $11, $91, $11, $91, $11, $87, $11, $91, $11, $87, $11, $91, $11, $91, $14, $87, $80, $13, $91
	.byte $82, $13, $87, $13, $91, $13, $91, $16, $87, $80, $18, $91, $82, $18, $87, $18, $91, $18, $91, $1b, $87, $48, $80, $1b
	.byte $ff, $9d, $13, $cd, $18, $a5, $0f, $a5, $48, $14, $a5, $11, $a5, $14, $a5, $11, $a5, $16, $cd, $18, $a5, $1b, $91, $1f
	.byte $91, $48, $1b, $ff, $9d, $13, $cd, $18, $cd, $48
	.byte $41, $31
	.word @song0ref14
	.byte $48, $1b, $a5, $18, $a5, $14, $cd, $19, $cd, $1b, $cd, $48, $84, $14, $ff, $ed, $00, $cd, $48, $ff, $ff, $bf
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
	.byte $41, $09
	.word @song0ref1
	.byte $48, $ff, $ff, $bf, $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $ff, $bf, $86, $40, $50
@song0ref141:
	.byte $87, $40, $4d, $87, $3c, $87, $38, $87, $35, $87, $38, $87, $3c
	.byte $41, $09
	.word @song0ref141
	.byte $30, $87, $35, $87, $38, $87, $3c, $87, $40, $4d, $87, $3a, $87, $35, $87, $31, $87, $2e, $87, $35, $87, $31, $87, $2e
	.byte $87, $29
@song0ref183:
	.byte $87, $30, $87, $2b, $87, $27, $87, $24, $87, $30, $87, $2b, $87, $27, $87, $24
@song0ref199:
	.byte $87
@song0ref200:
	.byte $30, $87, $33, $87, $37, $87, $3c, $87, $30, $87, $33, $87, $37, $87, $3c
	.byte $41, $10
	.word @song0ref199
@song0ref218:
	.byte $87, $27, $87, $2b, $87, $2e, $87, $33, $87, $27, $87, $2b, $87, $2e, $87, $33, $87, $2c, $87, $30, $87, $33, $87, $38
	.byte $87, $2c, $87, $30, $87, $33, $87, $38
@song0ref250:
	.byte $87, $25, $87, $29, $87, $2c, $87, $31, $87, $25, $87, $29, $87, $2c, $87, $31
	.byte $41, $10
	.word @song0ref250
	.byte $41, $21
	.word @song0ref218
@song0ref272:
	.byte $3c, $87, $37, $87, $33, $87, $30, $87, $3c, $87, $37, $87, $33, $87, $30
	.byte $41, $11
	.word @song0ref183
@song0ref290:
	.byte $27, $87, $24, $87, $1f, $87, $1b, $87, $27, $87, $24, $87, $1f, $87, $1b, $87, $20, $87, $1b, $87, $18, $87, $14, $87
	.byte $20, $87, $1b, $87, $18, $87, $14, $87, $2c, $91, $2c, $91, $29, $91, $29, $91, $2c, $91, $2c, $91, $29, $91, $29, $91
	.byte $2e, $91, $2e, $91, $2e, $91, $2e, $91, $29, $91, $29, $91, $2e, $91, $31, $91
	.byte $41, $0f
	.word @song0ref200
	.byte $41, $10
	.word @song0ref199
	.byte $41, $30
	.word @song0ref218
	.byte $41, $10
	.word @song0ref250
	.byte $41, $21
	.word @song0ref218
	.byte $41, $0f
	.word @song0ref272
	.byte $41, $11
	.word @song0ref183
	.byte $41, $20
	.word @song0ref290
	.byte $18, $87, $1b, $87, $20, $87, $1b, $87, $14, $87, $18, $87, $1b, $91, $20, $91, $1b, $91, $18, $91, $14, $91, $19, $91
	.byte $1d, $91, $20, $91, $25, $91, $1b, $91, $1f, $91, $22, $91, $27, $91, $88, $30, $91, $30, $91, $30, $91, $30, $91, $30
	.byte $91, $30, $91, $30, $91, $30
@song0ref432:
	.byte $91, $27, $91, $27, $91, $27, $91, $27, $91, $2c, $91, $2c, $91, $2c, $91, $2c, $91, $25, $91, $25, $91, $25, $91, $25
	.byte $91, $25, $91, $25, $91, $25, $91, $25
	.byte $41, $11
	.word @song0ref432
@song0ch1loop:
@song0ref468:
	.byte $00, $ff, $ff, $bd
@song0ref472:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $8a
@song0ref491:
	.byte $24, $cd, $27, $cd, $2b, $cd, $30, $cd, $20, $cd, $25, $cd, $27, $cd, $2b, $cd, $24, $cd, $27, $cd, $2b, $cd, $30, $cd
	.byte $24, $a5, $1d, $91, $1d, $91, $24, $a5, $1d, $91, $1d, $91, $25, $a5, $25, $a5, $22, $a5, $25, $91, $29, $91
	.byte $41, $10
	.word @song0ref491
	.byte $2b, $ff, $9d, $24, $ff, $9d, $1b, $a5, $1b, $a5, $1b, $cd, $20, $cd, $22, $cd, $8c, $1d, $a5, $1d, $f5, $22, $a5, $22
	.byte $f5, $19, $a5, $19, $f5, $1f, $a5, $1f, $f5
@song0ch2loop:
	.byte $41, $0d
	.word @song0ref468
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $8e
@song0ref587:
	.byte $23, $a5, $23, $a5, $21, $a5, $00, $a5, $23, $a5, $23, $a5, $21, $a5, $00, $a5
	.byte $41, $10
	.word @song0ref587
	.byte $41, $10
	.word @song0ref587
@song0ref609:
	.byte $21, $a5, $20, $a5, $21
@song0ref614:
	.byte $a5, $20, $a5, $21, $a5, $00, $a5, $20, $a5, $20, $a5, $20
	.byte $41, $0b
	.word @song0ref614
	.byte $21, $a5, $00, $a5
	.byte $41, $11
	.word @song0ref609
	.byte $41, $0b
	.word @song0ref614
	.byte $21, $a5, $00, $a5
	.byte $41, $09
	.word @song0ref472
@song0ch3loop:
	.byte $41, $09
	.word @song0ref472
	.byte $ff, $ff, $bf, $42
	.word @song0ch3loop
@song0ch4:
@song0ref656:
	.byte $02, $91, $02, $91, $02, $91, $02, $91
@song0ref664:
	.byte $02, $87, $02, $87, $02, $87, $02, $87, $02, $87, $02, $87, $02, $87, $02, $87
@song0ref680:
	.byte $06, $91, $02, $91, $06, $91, $02, $91, $07, $91, $07, $91, $04, $91, $07, $91, $04
@song0ref697:
	.byte $91, $02, $91, $04, $91, $02, $91, $04, $91, $02, $91, $04, $91, $02, $91
	.byte $41, $0a
	.word @song0ref680
	.byte $02, $91, $07, $91
	.byte $41, $09
	.word @song0ref656
@song0ref722:
	.byte $91, $02
@song0ref724:
	.byte $91, $02, $91, $02, $91, $02, $91, $01, $a5, $04, $91, $02, $91, $07, $91, $02, $91, $07
	.byte $41, $0f
	.word @song0ref697
	.byte $04, $91, $02, $91
	.byte $41, $0a
	.word @song0ref680
	.byte $02, $91, $07
	.byte $41, $09
	.word @song0ref722
	.byte $02, $91, $05, $91, $05, $91, $05, $91, $05
	.byte $41, $09
	.word @song0ref722
	.byte $06, $87, $06, $87, $06, $87, $06, $87, $06, $87, $06, $87, $06, $87, $06, $87, $03, $91, $05, $91, $03, $91, $05, $91
	.byte $04, $91, $05, $91, $04, $91, $05, $91, $06, $91, $05, $91, $06, $91, $05, $91, $07, $91, $05, $91, $07, $91, $05
	.byte $41, $09
	.word @song0ref722
	.byte $41, $20
	.word @song0ref664
	.byte $41, $09
	.word @song0ref656
	.byte $41, $12
	.word @song0ref724
	.byte $41, $0f
	.word @song0ref697
	.byte $04, $91, $02, $91
	.byte $41, $0a
	.word @song0ref680
	.byte $02, $91, $07, $91, $02, $91, $02, $91
@song0ref847:
	.byte $04, $91, $02, $91, $00, $91, $01, $a5, $07, $91, $00, $91, $02, $91, $06, $91, $02, $91, $06, $91, $06, $91, $06, $91
	.byte $01
@song0ref872:
	.byte $a5
@song0ref873:
	.byte $02, $91
@song0ref875:
	.byte $00, $91, $02, $91, $00, $91, $01, $a5, $00, $a5, $02, $91, $03, $91, $02, $91, $00, $91, $01, $a5, $03
	.byte $41, $0f
	.word @song0ref872
	.byte $41, $0a
	.word @song0ref875
@song0ch4loop:
	.byte $41, $0e
	.word @song0ref873
	.byte $41, $0c
	.word @song0ref875
	.byte $41, $28
	.word @song0ref847
	.byte $41, $0c
	.word @song0ref875
	.byte $41, $1a
	.word @song0ref847
	.byte $42
	.word @song0ch4loop
