; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Top of the Bell Curve:

.export _music_data_top_of_the_bell_curve:=music_data_top_of_the_bell_curve

music_data_top_of_the_bell_curve:
	.byte 2
	.word @instruments
	.word @samples-4
; 00 : Too Fuckin Happy
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Accelerating
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_top_of_the_bell_curve
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env5,@env9,@env13,@env0 ; 00 : Noise: Drum 1
	.word @env18,@env12,@env13,@env0 ; 01 : Noise: HighHat 1
	.word @env19,@env12,@env14,@env0 ; 02 : Square: Lead 2
	.word @env6,@env12,@env13,@env8 ; 03 : Square: rise vibrato
	.word @env4,@env12,@env16,@env0 ; 04 : Square: Lead 1
	.word @env2,@env7,@env13,@env0 ; 05 : Noise: Drum 2
	.word @env1,@env12,@env3,@env0 ; 06 : Square: Bwaaaa
	.word @env11,@env12,@env13,@env0 ; 07 : Triangle: 1
	.word @env10,@env15,@env13,@env0 ; 08 : Triangle: Bass
	.word @env11,@env12,@env13,@env17 ; 09 : Triangle: vibrato

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c0,$02,$c1,$02,$c2,$05,$c3,$33,$c4,$0d,$c5,$09,$c6,$00,$0d
@env2:
	.byte $00,$cf,$02,$c6,$c3,$c1,$c0,$00,$06
@env3:
	.byte $c3,$7f,$00,$00
@env4:
	.byte $00,$c4,$c4,$c6,$c6,$c7,$c7,$c8,$00,$07
@env5:
	.byte $00,$cf,$ce,$cd,$c8,$c4,$c0,$00,$06
@env6:
	.byte $00,$c3,$c5,$c5,$c6,$c6,$c7,$02,$c8,$00,$08
@env7:
	.byte $c0,$c3,$c0,$00,$02
@env8:
	.byte $00,$c0,$0d,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$00,$03
@env9:
	.byte $be,$c0,$00,$01
@env10:
	.byte $00,$cc,$7f,$00,$02
@env11:
	.byte $00,$cf,$7f,$00,$02
@env12:
	.byte $c0,$7f,$00,$01
@env13:
	.byte $7f,$00,$00
@env14:
	.byte $c2,$7f,$00,$00
@env15:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$00,$09
@env16:
	.byte $c1,$7f,$00,$00
@env17:
	.byte $00,$c0,$13,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$00,$03
@env18:
	.byte $00,$c9,$c8,$c4,$c2,$c0,$00,$05
@env19:
	.byte $00,$c5,$c6,$c7,$c7,$c8,$c9,$00,$06

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $88
@song0ref6:
	.byte $0d, $97, $00, $8b, $0f, $97, $11, $89, $00, $8d, $14, $97, $11, $8b, $00, $89, $0c, $89, $00, $8d, $14, $89, $11, $8b
	.byte $0d, $8b, $11, $97, $48, $0a, $97, $00, $8b, $0c, $97, $0d, $89, $00, $8d, $11, $a5, $00, $89, $08, $89, $00, $8d, $0a
	.byte $97, $11, $8b, $0a, $97, $48, $0d, $8b, $0a, $89, $06, $8b, $0d, $97, $0a, $8b, $00, $8b, $0d, $89, $0a, $8b, $06, $8b
	.byte $00, $89, $0d, $8b, $00, $8b, $06, $97, $0a, $8b, $06, $97, $48, $00, $8b, $0c, $8b, $00, $89, $0f, $97, $0c, $8b, $00
	.byte $8b, $0f, $89, $0c, $8b, $08, $8b, $00, $89, $0f, $8b, $00, $8b, $08, $97, $0c, $8b, $08, $97, $48
	.byte $41, $70
	.word @song0ref6
	.byte $48, $00, $ff, $ed, $48
	.byte $41, $70
	.word @song0ref6
	.byte $48
	.byte $41, $70
	.word @song0ref6
	.byte $48, $00, $ff, $ed, $48
	.byte $41, $70
	.word @song0ref6
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $ef, $ff, $ef, $8c, $12, $ff, $ed, $14, $ff, $ed, $19, $ff, $ed, $16, $ff, $ed, $12, $ff, $ed, $14, $ff, $ed, $19
	.byte $ff, $ed, $84
@song0ref176:
	.byte $19, $97, $00, $8b, $1b, $97, $1d, $89, $00, $8d, $20, $97, $1d, $8b, $00, $89, $18, $89, $00, $8d, $20, $89, $1d, $8b
	.byte $19, $8b, $1d, $97, $16, $97, $00, $8b, $18, $97, $19, $89, $00, $8d, $1d, $a5, $00, $89, $14, $89, $00, $8d, $16, $97
	.byte $1d, $8b, $16, $97, $19, $8b, $16, $89, $12, $8b, $19, $97, $16, $8b, $00, $8b, $19, $89, $16, $8b, $12, $8b, $00, $89
	.byte $19, $8b, $00, $8b, $12, $97, $16, $8b, $12, $97, $00, $8b, $18, $8b, $00, $89, $1b, $97, $18, $8b, $00, $8b, $1b, $89
	.byte $18, $8b, $14, $8b, $00, $89, $1b, $8b, $00, $8b, $14, $97, $18, $8b, $00, $97, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $ff, $ef
	.byte $41, $70
	.word @song0ref176
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $00, $8b, $8e
@song0ref308:
	.byte $19, $89, $00, $8b, $19
@song0ref313:
	.byte $97, $19, $8b, $00, $8b, $19, $89, $19, $8b, $19, $8b, $00, $89, $19, $8b, $00, $8b, $19, $89, $19, $8b, $19, $8b, $00
	.byte $89, $19, $8b, $00, $8b, $16, $89, $00, $8b, $16, $97, $16, $8b, $00, $8b, $16, $89, $16, $8b, $16, $8b, $00, $89, $16
	.byte $8b, $00, $8b, $16, $89, $16, $8b, $16, $8b, $00, $89, $16, $8b, $00, $8b, $1e, $89, $00, $8b, $1e, $97, $1e, $8b, $00
	.byte $8b, $1e, $89, $1e, $8b, $1e, $8b, $00, $89, $1e, $8b, $00, $8b, $1e, $89, $1e, $8b, $1e, $8b, $00, $89, $1e, $8b, $00
	.byte $8b, $20, $89, $00, $8b, $20, $97, $20, $8b, $00, $8b, $20, $89, $20, $8b, $20, $8b, $00, $89, $20, $8b, $00, $8b, $20
	.byte $89, $20, $8b, $20, $8b, $00, $89, $20, $8b, $00, $8b
	.byte $41, $88
	.word @song0ref308
@song0ref447:
	.byte $19, $89, $00, $8b, $19, $87, $00, $8d, $19, $8b, $00, $8b, $19, $89, $00, $8b, $19, $8b, $00, $89, $19, $85, $19, $83
	.byte $19, $83, $19, $85, $19, $83, $19, $83, $19, $85, $19, $83, $14, $8b, $00, $83, $11, $83, $11, $85, $11
@song0ref492:
	.byte $83, $00, $8b, $19, $89, $00, $8b, $19, $91, $00, $83, $19, $8b, $00, $8b, $19, $89, $00, $8b, $19, $91, $00, $83, $19
	.byte $8b, $00, $8b, $19, $83, $00, $83, $19, $85, $00, $83, $19, $83, $00, $85, $19, $83, $00, $83, $19, $85, $00, $83, $8d
	.byte $16, $89, $00, $8b, $16, $91, $00, $83, $16, $99, $16, $89, $00, $8b, $16, $91, $00, $83, $16, $99, $16, $83, $00, $83
	.byte $16, $85, $00, $83, $16, $83, $00, $85, $16, $83, $00, $83, $16, $85, $00, $83, $8d, $1e, $89, $00, $8b, $1e, $91, $00
	.byte $83, $1e, $8b, $00, $8b, $1e, $89, $00, $8b, $1e, $91, $00, $83, $1e, $8b, $00, $8b, $1e, $83, $00, $83, $1e, $85, $00
	.byte $83, $1e, $83, $00, $85, $1e, $83, $00, $83, $1e, $85, $00, $83, $8d, $20, $89, $00, $8b, $20, $91, $00, $83, $20, $8b
	.byte $00, $8b, $20, $89, $00, $8b, $20, $91, $00, $83, $20, $8b, $00, $8b, $20, $83, $00, $83, $20, $85, $00, $83, $20, $83
	.byte $00, $85, $20, $83, $00, $83, $20, $85, $00
	.byte $41, $2f
	.word @song0ref492
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $00, $8b
	.byte $41, $35
	.word @song0ref447
	.byte $41, $81
	.word @song0ref313
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $00, $8b, $80
@song0ref693:
	.byte $24, $89, $00, $8b
@song0ref697:
	.byte $25, $97, $82, $2f, $8b, $00, $8b, $80, $24, $89, $82, $31, $89, $00, $80, $25, $8b, $00, $89, $82, $2f, $8b, $00, $8b
	.byte $80, $24, $89, $82, $31, $8b, $80, $24, $8b, $00, $89, $24, $8b, $00, $8b
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
@song0ref757:
	.byte $8a, $24, $89, $00, $8b, $24, $8b, $00, $89, $24, $8b, $00, $8b, $24, $89, $82, $31, $8b, $00, $97, $8a, $24, $8b, $80
	.byte $24, $8b, $24, $89, $8a, $24, $8b, $00, $8b, $80, $27, $89, $27, $8b, $00, $8b
@song0ref797:
	.byte $24, $89, $00, $8b, $26, $97, $82, $2f, $8b, $00, $8b, $80, $24, $89, $00, $8b, $26, $97, $82, $2e, $8b, $00, $8b, $80
	.byte $24, $89, $24, $8b, $24, $8b, $24, $89, $82, $2d, $8b, $00, $8b, $80
	.byte $41, $20
	.word @song0ref797
	.byte $80
	.byte $41, $20
	.word @song0ref797
	.byte $80
	.byte $41, $20
	.word @song0ref797
	.byte $80
	.byte $41, $20
	.word @song0ref797
	.byte $80
	.byte $41, $1f
	.word @song0ref797
	.byte $ff, $ed, $ff, $ef, $00, $8b
	.byte $41, $26
	.word @song0ref757
	.byte $41, $1f
	.word @song0ref697
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $21
	.word @song0ref693
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref879:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $41, $0e
	.word @song0ref879
	.byte $41, $0e
	.word @song0ref879
	.byte $ff, $ef, $42
	.word @song0ch4loop
@song1ch0:
	.byte $88
@song1ref2:
	.byte $05, $87, $0c, $87, $05, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00, $87, $0c, $87, $00, $87
	.byte $0c, $87, $84, $08, $87, $88, $0c, $87, $00, $87, $08, $87, $00, $87, $08, $87, $00, $87, $08, $87, $00, $9b, $48, $03
	.byte $87, $0a, $87, $03, $87, $00, $87, $03, $87, $00, $87, $03, $87, $00, $87, $03, $87, $84, $06, $87, $88, $0a, $87, $00
	.byte $87, $0a, $87, $00, $87, $0a, $87, $00, $87, $06, $87, $00, $87, $06, $87, $00, $87, $06, $87, $00, $9b, $48, $0a, $87
	.byte $11, $87, $0a, $87, $00, $87, $0a, $87, $00, $87, $0a, $87, $00, $87, $0a, $87, $84, $0d, $87, $88, $11, $87, $00, $87
	.byte $11, $87, $00, $87, $11, $87, $00, $87, $0d, $87, $00, $87, $0d, $87, $00, $87, $0d, $87, $00, $9b, $48
	.byte $41, $84
	.word @song1ref2
	.byte $48
	.byte $41, $84
	.word @song1ref2
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song1ref154:
	.byte $05, $87, $0c, $87, $05, $87, $0c, $87, $05, $87, $0c, $87, $05, $87, $0c, $87, $05, $87, $0c, $87, $05, $87, $0c, $87
	.byte $05, $87, $84, $08, $87, $88, $0c, $87, $05, $87, $08, $87, $05, $87, $08, $87, $05, $87, $08, $87, $05, $87, $08, $87
	.byte $05, $87, $48, $03, $87, $0a, $87, $03, $87, $0a, $87, $03, $87, $0a, $87, $03, $87, $0a, $87, $03, $87, $84, $06, $87
	.byte $88, $0a, $87, $03, $87, $0a, $87, $06, $87, $0a, $87, $03, $87, $06, $87, $0a, $87, $06, $87, $0a, $87, $06, $87, $0a
	.byte $87, $06, $87, $00, $87, $48, $0a, $87, $11, $87, $0a, $87, $11, $87, $0a, $87, $11, $87, $0a, $87, $11, $87, $0a, $87
	.byte $84, $0d, $87, $88, $11, $87, $0d, $87, $11, $87, $0d, $87, $11, $87, $00, $87, $0d, $87, $11, $87, $0d, $87, $11, $87
	.byte $0d, $87, $11, $87, $0a, $87, $11, $87, $48
	.byte $41, $90
	.word @song1ref154
	.byte $42
	.word @song1ch0loop
@song1ch1:
	.byte $ff, $ef, $ff, $ef, $cf, $84, $16, $87, $19, $87, $1d, $87, $00, $87, $86, $1d, $f5, $00, $cd, $84, $11, $87, $14, $87
	.byte $18, $87, $00, $87, $86, $18, $f5, $84, $0f, $87, $12, $87, $16, $87, $00, $87, $86, $16, $a5, $84, $0f, $87, $12, $87
	.byte $16, $87, $00, $87, $86, $16, $f5, $84, $16, $87, $19, $87, $1d, $87, $00, $87, $86, $1d, $a5, $84, $16, $87, $19, $87
	.byte $1d, $87, $00, $87, $86, $1d, $f5
@song1ref392:
	.byte $84, $11, $87, $14, $87, $18, $87, $00, $87, $86, $18, $a5, $84, $11, $87, $14, $87, $18, $87, $00, $87, $86, $18, $a5
	.byte $84, $11, $87, $14, $87, $18, $87, $00, $87, $86, $18, $a5, $84, $0f, $87, $12, $87, $16, $87, $00, $87, $86, $16, $a5
	.byte $84, $0f, $87, $12, $87, $16, $87, $00, $87, $86, $16, $a5, $84, $0f, $87, $12, $87, $16, $87, $00, $87, $86, $16, $a5
	.byte $84, $16, $87, $19, $87, $1d, $87, $00, $87, $86, $1d, $a5, $84, $16, $87, $19, $87, $1d, $87, $00, $87, $86, $1d, $a5
	.byte $84, $16, $87, $19, $87, $1d, $87, $00, $87, $86, $1d, $a5
@song1ch1loop:
	.byte $41, $5a
	.word @song1ref392
	.byte $41, $5a
	.word @song1ref392
	.byte $42
	.word @song1ch1loop
@song1ch2:
	.byte $90
@song1ref511:
	.byte $0d, $87, $0d, $87, $0d, $87, $00, $87, $0d, $87, $00, $9b, $0d, $87, $00, $9b, $0d, $87, $00, $9b, $0d, $87, $00, $9b
	.byte $0d, $87, $00, $9b
	.byte $41, $1c
	.word @song1ref511
	.byte $41, $1c
	.word @song1ref511
	.byte $41, $1c
	.word @song1ref511
	.byte $41, $1c
	.word @song1ref511
	.byte $0d, $87, $0d, $87, $0d, $87, $00, $87, $0d, $87, $00, $9b, $0d, $87, $0d, $87, $0d, $87, $00, $87, $0d, $87, $00, $9b
	.byte $0d, $87, $00, $87, $0d, $87, $00, $87, $0d, $87, $00, $9b, $92
@song1ref588:
	.byte $35, $87, $30, $87, $2c, $87, $29, $87, $24, $ff, $c5, $33, $87, $30, $87, $2a, $87, $27, $87, $22, $ff, $c5, $3a, $87
	.byte $35, $87, $31, $87, $2e, $87, $29, $ff, $c5
@song1ch2loop:
	.byte $41, $21
	.word @song1ref588
	.byte $41, $21
	.word @song1ref588
	.byte $42
	.word @song1ch2loop
@song1ch3:
	.byte $80
@song1ref632:
	.byte $27, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $9b, $29, $87, $00, $9b, $27, $91, $00, $91, $27, $91, $00, $91
	.byte $27, $91, $00, $91
	.byte $41, $1c
	.word @song1ref632
	.byte $41, $1c
	.word @song1ref632
	.byte $41, $1c
	.word @song1ref632
	.byte $41, $1c
	.word @song1ref632
@song1ref672:
	.byte $27, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $9b, $27, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $9b
	.byte $27, $87, $00, $87, $27, $87, $00, $87, $27, $87, $00, $9b
	.byte $41, $24
	.word @song1ref672
	.byte $41, $1c
	.word @song1ref632
	.byte $41, $1c
	.word @song1ref632
@song1ch3loop:
	.byte $41, $24
	.word @song1ref672
	.byte $41, $24
	.word @song1ref672
	.byte $41, $24
	.word @song1ref672
@song1ref727:
	.byte $27, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $87, $27, $87, $00, $87, $27, $87, $27, $87, $27, $87, $00, $87
	.byte $27, $87, $00, $87, $27, $87, $00, $87
	.byte $41, $20
	.word @song1ref727
	.byte $41, $20
	.word @song1ref727
	.byte $41, $20
	.word @song1ref727
	.byte $27, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $87, $27, $87, $00, $87, $42
	.word @song1ch3loop
@song1ch4:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
@song1ch4loop:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song1ch4loop
