; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4 ; 00 : recombined
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env3,@env4,@env5,@env0 ; 00 : Instrument 1
	.word @env1,@env4,@env5,@env0 ; 01 : Instrument 2
	.word @env2,@env4,@env5,@env0 ; 02 : Instrument 3

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$ca,$cc,$cc,$cd,$cd,$ce,$ce,$cf,$00,$08
@env2:
	.byte $00,$cf,$cd,$cc,$ca,$c3,$00,$05
@env3:
	.byte $00,$cf,$7f,$00,$02
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ref1:
	.byte $7a, $80
@song0ref3:
	.byte $0d, $a5, $43, $11, $a5, $43, $0d, $a5, $43, $14, $a5, $43, $0d, $a5, $43, $0f, $a5, $43, $0d, $a5, $43, $12, $a5, $47
	.byte $43
	.byte $41, $10
	.word @song0ref3
@song0ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
	.byte $41, $10
	.word @song0ref1
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
@song0ref58:
	.byte $47, $7d, $43, $0d, $a5, $43, $11, $a5, $43, $0d, $a5, $43, $14, $a5, $43, $0d, $a5, $43, $16, $a5, $43, $11, $a5, $43
	.byte $18, $a5, $47, $7a, $43
	.byte $41, $10
	.word @song0ref3
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
	.byte $41, $10
	.word @song0ref58
	.byte $47, $7a, $43
	.byte $41, $10
	.word @song0ref3
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
	.byte $47, $43
	.byte $41, $10
	.word @song0ref3
	.byte $41, $10
	.word @song0ref58
	.byte $47, $7a, $43
	.byte $41, $10
	.word @song0ref3
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $ff, $bf, $ff, $ff, $bf
@song0ch1loop:
	.byte $82
@song0ref159:
	.byte $1e, $ff, $9d, $22, $ff, $9d, $20, $ff, $9d, $1d, $ff, $9d
	.byte $41, $0c
	.word @song0ref159
@song0ref174:
	.byte $20, $cd, $00, $a5, $24, $a5, $1e, $cd, $22, $cd, $24, $91, $00, $91, $24, $91, $00, $91, $24, $a5, $22, $a5, $27, $a5
	.byte $29, $a5, $2c, $a5, $2e, $a5
@song0ref204:
	.byte $20, $ff, $9d, $1d, $ff, $9d, $1e, $ff, $9d, $22, $ff, $9d
	.byte $41, $2a
	.word @song0ref174
	.byte $41, $0c
	.word @song0ref204
	.byte $20, $cd, $00, $a5, $24, $a5, $1e, $cd, $22, $cd, $20, $cd, $00, $a5, $24, $a5, $1e, $cd, $22, $cd
	.byte $41, $1e
	.word @song0ref174
	.byte $00, $ff, $ff, $bd, $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $ff, $bf, $ff, $ff, $bf
@song0ch2loop:
	.byte $ff, $ff, $bf
@song0ref262:
	.byte $84, $33, $ff, $9d, $30, $ff, $9d, $80, $31, $ff, $9d, $35, $ff, $9d
	.byte $41, $0c
	.word @song0ref262
	.byte $00, $ff, $ff, $bd
	.byte $41, $0c
	.word @song0ref262
	.byte $84, $33, $ff, $9d, $30, $ff, $9d
@song0ref293:
	.byte $43, $3d, $a5, $43, $31, $a5, $00, $a5, $3d, $a5, $43, $33, $a5, $43, $36, $a5, $43, $3a, $a5, $43, $3f, $a5, $80, $3d
	.byte $ff, $9d, $38, $ff, $9d, $31, $ff, $9d, $35, $ff, $9d
	.byte $41, $0c
	.word @song0ref262
	.byte $84
@song0ref332:
	.byte $3d, $a5, $31, $a5, $00, $a5, $3d, $a5, $33, $a5, $35, $a5, $3a, $a5, $33, $a5
	.byte $41, $10
	.word @song0ref332
	.byte $41, $10
	.word @song0ref332
	.byte $41, $16
	.word @song0ref293
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $ff, $bf
@song0ref363:
	.byte $7d, $84
@song0ref365:
	.byte $16, $91, $14, $91, $00, $a5, $1b, $91, $00, $b9, $16, $91, $18, $91, $00, $a5, $1b, $91, $00, $b9
@song0ch3loop:
	.byte $41, $14
	.word @song0ref363
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $41, $14
	.word @song0ref365
	.byte $ff, $ff, $bf, $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $ff, $bf, $ff, $ff, $bf
@song0ch4loop:
@song0ref453:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
	.byte $41, $0c
	.word @song0ref453
	.byte $41, $0c
	.word @song0ref453
	.byte $41, $0c
	.word @song0ref453
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song0ch4loop
