; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Top of the Bell Curve:

.export _music_data_accelerating:=music_data_accelerating

music_data_accelerating:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Accelerating
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_accelerating
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env14,@env8,@env10,@env0 ; 00 : Square: Lead 2
	.word @env3,@env8,@env9,@env4 ; 01 : Square: rise vibrato
	.word @env1,@env8,@env12,@env0 ; 02 : Square: Lead 1
	.word @env6,@env11,@env9,@env0 ; 03 : Triangle: Bass
	.word @env7,@env8,@env9,@env13 ; 04 : Triangle: vibrato
	.word @env2,@env5,@env9,@env0 ; 05 : Noise: Drum 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c4,$c4,$c6,$c6,$c7,$c7,$c8,$00,$07
@env2:
	.byte $00,$cf,$ce,$cd,$c8,$c4,$c0,$00,$06
@env3:
	.byte $00,$c3,$c5,$c5,$c6,$c6,$c7,$02,$c8,$00,$08
@env4:
	.byte $00,$c0,$0d,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$00,$03
@env5:
	.byte $be,$c0,$00,$01
@env6:
	.byte $00,$cc,$7f,$00,$02
@env7:
	.byte $00,$cf,$7f,$00,$02
@env8:
	.byte $c0,$7f,$00,$01
@env9:
	.byte $7f,$00,$00
@env10:
	.byte $c2,$7f,$00,$00
@env11:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$00,$09
@env12:
	.byte $c1,$7f,$00,$00
@env13:
	.byte $00,$c0,$13,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$00,$03
@env14:
	.byte $00,$c5,$c6,$c7,$c7,$c8,$c9,$00,$06

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $84
@song0ref2:
	.byte $05, $87, $0c, $87, $05, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00, $87, $05, $87, $00, $87, $0c, $87, $00, $87
	.byte $0c, $87, $80, $08, $87, $84, $0c, $87, $00, $87, $08, $87, $00, $87, $08, $87, $00, $87, $08, $87, $00, $9b, $48, $03
	.byte $87, $0a, $87, $03, $87, $00, $87, $03, $87, $00, $87, $03, $87, $00, $87, $03, $87, $80, $06, $87, $84, $0a, $87, $00
	.byte $87, $0a, $87, $00, $87, $0a, $87, $00, $87, $06, $87, $00, $87, $06, $87, $00, $87, $06, $87, $00, $9b, $48, $0a, $87
	.byte $11, $87, $0a, $87, $00, $87, $0a, $87, $00, $87, $0a, $87, $00, $87, $0a, $87, $80, $0d, $87, $84, $11, $87, $00, $87
	.byte $11, $87, $00, $87, $11, $87, $00, $87, $0d, $87, $00, $87, $0d, $87, $00, $87, $0d, $87, $00, $9b, $48
	.byte $41, $84
	.word @song0ref2
	.byte $48
	.byte $41, $84
	.word @song0ref2
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref154:
	.byte $05, $87, $0c, $87, $05, $87, $0c, $87, $05, $87, $0c, $87, $05, $87, $0c, $87, $05, $87, $0c, $87, $05, $87, $0c, $87
	.byte $05, $87, $80, $08, $87, $84, $0c, $87, $05, $87, $08, $87, $05, $87, $08, $87, $05, $87, $08, $87, $05, $87, $08, $87
	.byte $05, $87, $48, $03, $87, $0a, $87, $03, $87, $0a, $87, $03, $87, $0a, $87, $03, $87, $0a, $87, $03, $87, $80, $06, $87
	.byte $84, $0a, $87, $03, $87, $0a, $87, $06, $87, $0a, $87, $03, $87, $06, $87, $0a, $87, $06, $87, $0a, $87, $06, $87, $0a
	.byte $87, $06, $87, $00, $87, $48, $0a, $87, $11, $87, $0a, $87, $11, $87, $0a, $87, $11, $87, $0a, $87, $11, $87, $0a, $87
	.byte $80, $0d, $87, $84, $11, $87, $0d, $87, $11, $87, $0d, $87, $11, $87, $00, $87, $0d, $87, $11, $87, $0d, $87, $11, $87
	.byte $0d, $87, $11, $87, $0a, $87, $11, $87, $48
	.byte $41, $90
	.word @song0ref154
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $ef, $ff, $ef, $cf, $80, $16, $87, $19, $87, $1d, $87, $00, $87, $82, $1d, $f5, $00, $cd, $80, $11, $87, $14, $87
	.byte $18, $87, $00, $87, $82, $18, $f5, $80, $0f, $87, $12, $87, $16, $87, $00, $87, $82, $16, $a5, $80, $0f, $87, $12, $87
	.byte $16, $87, $00, $87, $82, $16, $f5, $80, $16, $87, $19, $87, $1d, $87, $00, $87, $82, $1d, $a5, $80, $16, $87, $19, $87
	.byte $1d, $87, $00, $87, $82, $1d, $f5
@song0ref392:
	.byte $80, $11, $87, $14, $87, $18, $87, $00, $87, $82, $18, $a5, $80, $11, $87, $14, $87, $18, $87, $00, $87, $82, $18, $a5
	.byte $80, $11, $87, $14, $87, $18, $87, $00, $87, $82, $18, $a5, $80, $0f, $87, $12, $87, $16, $87, $00, $87, $82, $16, $a5
	.byte $80, $0f, $87, $12, $87, $16, $87, $00, $87, $82, $16, $a5, $80, $0f, $87, $12, $87, $16, $87, $00, $87, $82, $16, $a5
	.byte $80, $16, $87, $19, $87, $1d, $87, $00, $87, $82, $1d, $a5, $80, $16, $87, $19, $87, $1d, $87, $00, $87, $82, $1d, $a5
	.byte $80, $16, $87, $19, $87, $1d, $87, $00, $87, $82, $1d, $a5
@song0ch1loop:
	.byte $41, $5a
	.word @song0ref392
	.byte $41, $5a
	.word @song0ref392
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $86
@song0ref511:
	.byte $0d, $87, $0d, $87, $0d, $87, $00, $87, $0d, $87, $00, $9b, $0d, $87, $00, $9b, $0d, $87, $00, $9b, $0d, $87, $00, $9b
	.byte $0d, $87, $00, $9b
	.byte $41, $1c
	.word @song0ref511
	.byte $41, $1c
	.word @song0ref511
	.byte $41, $1c
	.word @song0ref511
	.byte $41, $1c
	.word @song0ref511
	.byte $0d, $87, $0d, $87, $0d, $87, $00, $87, $0d, $87, $00, $9b, $0d, $87, $0d, $87, $0d, $87, $00, $87, $0d, $87, $00, $9b
	.byte $0d, $87, $00, $87, $0d, $87, $00, $87, $0d, $87, $00, $9b, $88
@song0ref588:
	.byte $35, $87, $30, $87, $2c, $87, $29, $87, $24, $ff, $c5, $33, $87, $30, $87, $2a, $87, $27, $87, $22, $ff, $c5, $3a, $87
	.byte $35, $87, $31, $87, $2e, $87, $29, $ff, $c5
@song0ch2loop:
	.byte $41, $21
	.word @song0ref588
	.byte $41, $21
	.word @song0ref588
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $8a
@song0ref632:
	.byte $27, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $9b, $29, $87, $00, $9b, $27, $91, $00, $91, $27, $91, $00, $91
	.byte $27, $91, $00, $91
	.byte $41, $1c
	.word @song0ref632
	.byte $41, $1c
	.word @song0ref632
	.byte $41, $1c
	.word @song0ref632
	.byte $41, $1c
	.word @song0ref632
@song0ref672:
	.byte $27, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $9b, $27, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $9b
	.byte $27, $87, $00, $87, $27, $87, $00, $87, $27, $87, $00, $9b
	.byte $41, $24
	.word @song0ref672
	.byte $41, $1c
	.word @song0ref632
	.byte $41, $1c
	.word @song0ref632
@song0ch3loop:
	.byte $41, $24
	.word @song0ref672
	.byte $41, $24
	.word @song0ref672
	.byte $41, $24
	.word @song0ref672
@song0ref727:
	.byte $27, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $87, $27, $87, $00, $87, $27, $87, $27, $87, $27, $87, $00, $87
	.byte $27, $87, $00, $87, $27, $87, $00, $87
	.byte $41, $20
	.word @song0ref727
	.byte $41, $20
	.word @song0ref727
	.byte $41, $20
	.word @song0ref727
	.byte $27, $87, $27, $87, $27, $87, $00, $87, $27, $87, $00, $87, $27, $87, $00, $87, $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
@song0ch4loop:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song0ch4loop
