; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Top of the Bell Curve:

.export _music_data_too_fuckin_happy:=music_data_too_fuckin_happy

music_data_too_fuckin_happy:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Too Fuckin Happy
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_too_fuckin_happy
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env5,@env7,@env10,@env0 ; 00 : Noise: Drum 1
	.word @env13,@env9,@env10,@env0 ; 01 : Noise: HighHat 1
	.word @env2,@env6,@env10,@env0 ; 02 : Noise: Drum 2
	.word @env4,@env9,@env12,@env0 ; 03 : Square: Lead 1
	.word @env1,@env9,@env3,@env0 ; 04 : Square: Bwaaaa
	.word @env14,@env9,@env11,@env0 ; 05 : Square: Lead 2
	.word @env8,@env9,@env10,@env0 ; 06 : Triangle: 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c0,$02,$c1,$02,$c2,$05,$c3,$33,$c4,$0d,$c5,$09,$c6,$00,$0d
@env2:
	.byte $00,$cf,$02,$c6,$c3,$c1,$c0,$00,$06
@env3:
	.byte $c3,$7f,$00,$00
@env4:
	.byte $00,$c4,$c4,$c6,$c6,$c7,$c7,$c8,$00,$07
@env5:
	.byte $00,$cf,$ce,$cd,$c8,$c4,$c0,$00,$06
@env6:
	.byte $c0,$c3,$c0,$00,$02
@env7:
	.byte $be,$c0,$00,$01
@env8:
	.byte $00,$cf,$7f,$00,$02
@env9:
	.byte $c0,$7f,$00,$01
@env10:
	.byte $7f,$00,$00
@env11:
	.byte $c2,$7f,$00,$00
@env12:
	.byte $c1,$7f,$00,$00
@env13:
	.byte $00,$c9,$c8,$c4,$c2,$c0,$00,$05
@env14:
	.byte $00,$c5,$c6,$c7,$c7,$c8,$c9,$00,$06

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $86
@song0ref6:
	.byte $0d, $97, $00, $8b, $0f, $97, $11, $89, $00, $8d, $14, $97, $11, $8b, $00, $89, $0c, $89, $00, $8d, $14, $89, $11, $8b
	.byte $0d, $8b, $11, $97, $48, $0a, $97, $00, $8b, $0c, $97, $0d, $89, $00, $8d, $11, $a5, $00, $89, $08, $89, $00, $8d, $0a
	.byte $97, $11, $8b, $0a, $97, $48, $0d, $8b, $0a, $89, $06, $8b, $0d, $97, $0a, $8b, $00, $8b, $0d, $89, $0a, $8b, $06, $8b
	.byte $00, $89, $0d, $8b, $00, $8b, $06, $97, $0a, $8b, $06, $97, $48, $00, $8b, $0c, $8b, $00, $89, $0f, $97, $0c, $8b, $00
	.byte $8b, $0f, $89, $0c, $8b, $08, $8b, $00, $89, $0f, $8b, $00, $8b, $08, $97, $0c, $8b, $08, $97, $48
	.byte $41, $70
	.word @song0ref6
	.byte $48, $00, $ff, $ed, $48
	.byte $41, $70
	.word @song0ref6
	.byte $48
	.byte $41, $70
	.word @song0ref6
	.byte $48, $00, $ff, $ed, $48
	.byte $41, $70
	.word @song0ref6
	.byte $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $ef, $ff, $ef, $88, $12, $ff, $ed, $14, $ff, $ed, $19, $ff, $ed, $16, $ff, $ed, $12, $ff, $ed, $14, $ff, $ed, $19
	.byte $ff, $ed, $8a
@song0ref176:
	.byte $19, $97, $00, $8b, $1b, $97, $1d, $89, $00, $8d, $20, $97, $1d, $8b, $00, $89, $18, $89, $00, $8d, $20, $89, $1d, $8b
	.byte $19, $8b, $1d, $97, $16, $97, $00, $8b, $18, $97, $19, $89, $00, $8d, $1d, $a5, $00, $89, $14, $89, $00, $8d, $16, $97
	.byte $1d, $8b, $16, $97, $19, $8b, $16, $89, $12, $8b, $19, $97, $16, $8b, $00, $8b, $19, $89, $16, $8b, $12, $8b, $00, $89
	.byte $19, $8b, $00, $8b, $12, $97, $16, $8b, $12, $97, $00, $8b, $18, $8b, $00, $89, $1b, $97, $18, $8b, $00, $8b, $1b, $89
	.byte $18, $8b, $14, $8b, $00, $89, $1b, $8b, $00, $8b, $14, $97, $18, $8b, $00, $97, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $ff, $ef
	.byte $41, $70
	.word @song0ref176
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $00, $8b, $8c
@song0ref308:
	.byte $19, $89, $00, $8b, $19
@song0ref313:
	.byte $97, $19, $8b, $00, $8b, $19, $89, $19, $8b, $19, $8b, $00, $89, $19, $8b, $00, $8b, $19, $89, $19, $8b, $19, $8b, $00
	.byte $89, $19, $8b, $00, $8b, $16, $89, $00, $8b, $16, $97, $16, $8b, $00, $8b, $16, $89, $16, $8b, $16, $8b, $00, $89, $16
	.byte $8b, $00, $8b, $16, $89, $16, $8b, $16, $8b, $00, $89, $16, $8b, $00, $8b, $1e, $89, $00, $8b, $1e, $97, $1e, $8b, $00
	.byte $8b, $1e, $89, $1e, $8b, $1e, $8b, $00, $89, $1e, $8b, $00, $8b, $1e, $89, $1e, $8b, $1e, $8b, $00, $89, $1e, $8b, $00
	.byte $8b, $20, $89, $00, $8b, $20, $97, $20, $8b, $00, $8b, $20, $89, $20, $8b, $20, $8b, $00, $89, $20, $8b, $00, $8b, $20
	.byte $89, $20, $8b, $20, $8b, $00, $89, $20, $8b, $00, $8b
	.byte $41, $88
	.word @song0ref308
@song0ref447:
	.byte $19, $89, $00, $8b, $19, $87, $00, $8d, $19, $8b, $00, $8b, $19, $89, $00, $8b, $19, $8b, $00, $89, $19, $85, $19, $83
	.byte $19, $83, $19, $85, $19, $83, $19, $83, $19, $85, $19, $83, $14, $8b, $00, $83, $11, $83, $11, $85, $11
@song0ref492:
	.byte $83, $00, $8b, $19, $89, $00, $8b, $19, $91, $00, $83, $19, $8b, $00, $8b, $19, $89, $00, $8b, $19, $91, $00, $83, $19
	.byte $8b, $00, $8b, $19, $83, $00, $83, $19, $85, $00, $83, $19, $83, $00, $85, $19, $83, $00, $83, $19, $85, $00, $83, $8d
	.byte $16, $89, $00, $8b, $16, $91, $00, $83, $16, $99, $16, $89, $00, $8b, $16, $91, $00, $83, $16, $99, $16, $83, $00, $83
	.byte $16, $85, $00, $83, $16, $83, $00, $85, $16, $83, $00, $83, $16, $85, $00, $83, $8d, $1e, $89, $00, $8b, $1e, $91, $00
	.byte $83, $1e, $8b, $00, $8b, $1e, $89, $00, $8b, $1e, $91, $00, $83, $1e, $8b, $00, $8b, $1e, $83, $00, $83, $1e, $85, $00
	.byte $83, $1e, $83, $00, $85, $1e, $83, $00, $83, $1e, $85, $00, $83, $8d, $20, $89, $00, $8b, $20, $91, $00, $83, $20, $8b
	.byte $00, $8b, $20, $89, $00, $8b, $20, $91, $00, $83, $20, $8b, $00, $8b, $20, $83, $00, $83, $20, $85, $00, $83, $20, $83
	.byte $00, $85, $20, $83, $00, $83, $20, $85, $00
	.byte $41, $2f
	.word @song0ref492
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $00, $8b
	.byte $41, $35
	.word @song0ref447
	.byte $41, $81
	.word @song0ref313
	.byte $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $00, $8b, $80
@song0ref693:
	.byte $24, $89, $00, $8b
@song0ref697:
	.byte $25, $97, $82, $2f, $8b, $00, $8b, $80, $24, $89, $82, $31, $89, $00, $80, $25, $8b, $00, $89, $82, $2f, $8b, $00, $8b
	.byte $80, $24, $89, $82, $31, $8b, $80, $24, $8b, $00, $89, $24, $8b, $00, $8b
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
@song0ref757:
	.byte $84, $24, $89, $00, $8b, $24, $8b, $00, $89, $24, $8b, $00, $8b, $24, $89, $82, $31, $8b, $00, $97, $84, $24, $8b, $80
	.byte $24, $8b, $24, $89, $84, $24, $8b, $00, $8b, $80, $27, $89, $27, $8b, $00, $8b
@song0ref797:
	.byte $24, $89, $00, $8b, $26, $97, $82, $2f, $8b, $00, $8b, $80, $24, $89, $00, $8b, $26, $97, $82, $2e, $8b, $00, $8b, $80
	.byte $24, $89, $24, $8b, $24, $8b, $24, $89, $82, $2d, $8b, $00, $8b, $80
	.byte $41, $20
	.word @song0ref797
	.byte $80
	.byte $41, $20
	.word @song0ref797
	.byte $80
	.byte $41, $20
	.word @song0ref797
	.byte $80
	.byte $41, $20
	.word @song0ref797
	.byte $80
	.byte $41, $1f
	.word @song0ref797
	.byte $ff, $ed, $ff, $ef, $00, $8b
	.byte $41, $26
	.word @song0ref757
	.byte $41, $1f
	.word @song0ref697
	.byte $41, $23
	.word @song0ref693
	.byte $41, $23
	.word @song0ref693
	.byte $41, $21
	.word @song0ref693
	.byte $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref879:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $41, $0e
	.word @song0ref879
	.byte $41, $0e
	.word @song0ref879
	.byte $ff, $ef, $42
	.word @song0ch4loop
